### ISSUE TITLE
පරිගණක පුහුණු මෘදුකාංගය - Excel Sheet

### ISSUE THREAD

**Issue by dkmahaarachchi** [buddhika75/td#12]
ඩොක්ටර්,
පුහුණු මෘදුකාංගයේ Excel Sheet එක Download කිරිමේදි Download කළ නොහැකිය. කරුණාකර එය සකසන මෙන් ඉල්ලා සිටිමි.  

ස්තුතියි...........

**Comment by buddhika75** [comment]
Done. Thanks. Please check.
